name: 'Zeno Dist Package'
description: 'Distribute a package to Zeno.'
inputs:
  zeno-server:
    required: true
  access-id:
    required: true
  access-secret:
    required: true
  service:
    required: true
  version:
    required: true
  file:
    required: true
  content-type:
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        OUTPUT=`curl -sS -X POST \
             -u '${{ inputs.access-id }}:${{ inputs.access-secret }}' \
             -d 'service=${{ inputs.service }}' \
             -d 'version=${{ inputs.version }}' \
             '${{ inputs.zeno-server }}/api/v1/packages/generate_presigned_upload_request?output=curl'`
        echo $OUTPUT
        STATUS=`echo $OUTPUT | grep -soP '(?<=ec":)\d+'`
        echo $STATUS
        if [[ $STATUS -ne 0 ]];then
            echo $OUTPUT
            exit -1
        fi
        echo 'uploading...'
        echo $OUTPUT
        echo $OUTPUT | curl -K - \
             --form-string 'Content-Type=${{ inputs.content-type }}' \
             -o out.xml
        echo 'uploaded'
        BUCKET=`grep -soP '(?<=Bucket>)[^<]+' out.xml`
        KEY=`grep -soP '(?<=Key>)[^<]+' out.xml`
        ETAG=`grep -soP '(?<=ETag>)[^<]+' out.xml`
        if [ "$BUCKET" = '' ];then
            echo 'upload fail'
            cat out.xml
            echo 'upload fail2'
            exit -1
        fi
        curl -sS -X POST \
             -u '${{ inputs.access-id }}:${{ inputs.access-secret }}' \
             -d 'service=${{ inputs.service }}' \
             -d 'version=${{ inputs.version }}' \
             -d "file={ \"Bucket\": \"$BUCKET\", \"Key\": \"$KEY\", \"ETag\": \"${ETAG//\"/\\\"}\", \"Location\": \"\" }"\
             '${{ inputs.zeno-server }}/api/v1/packages/create_with_file_info'
